# Generated by Django 5.0.7 on 2024-07-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmodel_nid_alter_patientmodel_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorModel',
        ),
    ]
