# Generated by Django 5.0.6 on 2024-07-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patientmodel_nid_alter_patientmodel_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctormodel')),
            ],
        ),
    ]
