# Generated by Django 5.0.6 on 2024-07-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmodel_nid_alter_patientmodel_phone_and_more'),
        ('vaccine_campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDoseBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dose_date', models.DateField()),
                ('second_dose_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_campaign.vaccinecampaignmodel')),
            ],
        ),
    ]
