# Generated by Django 5.0.6 on 2024-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0003_vaccinereviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedosebookingmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
