# Generated by Django 5.0.7 on 2024-07-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('vaccine_campaign', '0004_vaccinedosebookingmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaignmodel',
            name='image',
            field=models.ImageField(default='media/vaccine-details.png', upload_to='vaccine-campaign/media/'),
        ),
        migrations.AlterField(
            model_name='vaccinecampaignmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctormodel'),
        ),
    ]
