# Generated by Django 5.0.7 on 2024-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0006_remove_vaccinecampaignmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaignmodel',
            name='image',
            field=models.ImageField(default='media/vaccine-details.png', upload_to='vaccine-campaign/media/'),
        ),
    ]
